### ISSUE TITLE
Same exact banner for Covidex and Neural Covidex

### ISSUE THREAD

**Issue by lintool** [castorini/covidex#10]
Both neural and non-neural versions should look exactly the same in the landing page, modulo differences in landing page text (and the neural vs. non-neural header).

That is, if I have both sites open in different tables, I should be able to tab back and forth and see exactly the same location for the search box, same height of the banner, etc. That way, we establish a consistent look and feel.

**Comment by edwinzhng** [comment]
This is 90% fixed, just need to match the icon on the search button and fix the padding on mobile.

**Comment by edwinzhng** [comment]
Let me know if you notice anything else

**Comment by lintool** [comment]
<img width="152" alt="Screen Shot 2020-04-07 at 7 39 34 AM" src="https://user-images.githubusercontent.com/313837/78664903-f2b1e000-78a2-11ea-8c59-ff73bdbc6448.png">

sorry, to be nitpicky, but the font of the search button is still slightly different... if you put the two interfaces in separate browser tabs and switch back and forth, it'll be apparent...

**Comment by edwinzhng** [comment]
Good catch! global CSS styles by default don't apply to buttons...

**Comment by lintool** [comment]
@edwinzhng Please add feedback link to the basic covidex when you get a chance?

**Comment by edwinzhng** [comment]
Font + feedback link have been added - should we close this now?
