### ISSUE TITLE
Add Github ribbon

### ISSUE THREAD

**Issue by lintool** [castorini/covidex#11]
https://github.blog/2008-12-19-github-ribbons/

Let's go with the red one, I think.

On both basic and neural ones. Neural href should redirect to this repo. Basic should redirect to https://github.com/castorini/anserini/blob/master/docs/experiments-covid.md

**Comment by nikhilro** [comment]
Hmm... I think we should get more opinions on this 😛

**Comment by edwinzhng** [comment]
I don't think these fit in with the site and they're pretty outdated. I'd rather put a Github logo + button in the navbar like https://huggingface.co/

**Comment by lintool** [comment]
Works for me. Just responding to @rodrigonogueira4 's comment that we should make link to GitHub obvious...

Once again, I've shown my age...
