### ISSUE TITLE
Is Covidex now Cydex?

### ISSUE THREAD

**Issue by bevankoopman** [castorini/covidex#115]
In the following [paper](https://cs.uwaterloo.ca/~jimmylin/publications/Ding_etal_SDP2020.pdf):

```bibtex
@inproceedings{ding2020cydex,
  title={Cydex: Neural Search Infrastructure for the Scholarly Literature},
  author={Ding, Shane and Zhang, Edwin and Lin, Jimmy},
  booktitle={Proceedings of the First Workshop on Scholarly Document Processing},
  pages={168--173},
  year={2020}
}
```

it describes Cydex as an extension of Covidex to decouple it from CORD. While the paper says Cydex is open source, there does not seem to be any URL to the source.

Is this repo for Cydex as well?

**Comment by lintool** [comment]
That is correct!
