### ISSUE TITLE
Feature request: filter the time window

### ISSUE THREAD

**Issue by lintool** [castorini/covidex#34]
This, I think we already know we need - reimplement facets!

**Comment by edwinzhng** [comment]
I assume we should add facet support on Pyserini first?

**Comment by felipemoraes** [comment]
Hi @lintool very interested in time window. I've currently plugged Covidex to SearchX, our collaborative search system, and we can't provide pagination for Covidex provider yet. See SearchX with Covidex working here:  `http://searchx-covid19.ewi.tudelft.nl/search?provider=covidex`

**Comment by lintool** [comment]
Yup, we're working on it right now!

**Comment by lintool** [comment]
@felipemoraes I'm playing with your system. I think it'd be nice to have some instructions on how to use it? For example, what's the group id?

**Comment by felipemoraes** [comment]
Hi @lintool indeed, we need to improve on that, right now there's an exclamation mark on group id explaining what is. `Share the group link with others to start a collaborative session. If you wish to test out a session with multiple users yourself you can open an incognito/private window.`
Of course, we can do better!

**Comment by edwinzhng** [comment]
Closing since we now have faceting
