### ISSUE TITLE
Update index of basic covidex

### ISSUE THREAD

**Issue by lintool** [castorini/covidex#51]
I don't think the Blacklight version has been updated in a while?

**Comment by edwinzhng** [comment]
Updated it 30 min ago, does it look like it didn't go through?

**Comment by edwinzhng** [comment]
Result #15 is from April 20th which should be from the newest dump: https://basic.covidex.ai/?f%5Byear%5D%5B%5D=2020&q=covid&search_field=contents

**Comment by lintool** [comment]
nope, my bad, I think we're good!
