### ISSUE TITLE
Retrieve related articles metadata from Pyserini index

### ISSUE THREAD

**Issue by edwinzhng** [castorini/covidex#54]
Currently, we download the `metadata.csv` file for related article search, and retrieve values from there. We should instead use Pyserini so that all article data is formatted in the same way and comes from the same place. This would require retrieving an article by ID from Pyserini, which I'm not sure is possible yet.

**Comment by lintool** [comment]
Is this what you're looking for? https://github.com/castorini/pyserini/blob/master/pyserini/search/pysearch.py#L239

**Comment by edwinzhng** [comment]
Yep! @x65han maybe you can tackle this when you get a chance?

**Comment by lintool** [comment]
Actually, since `cord_ui` is indexed at as `id` in Anserini, this should just work:
https://github.com/castorini/pyserini/blob/master/pyserini/search/pysearch.py#L221

**Comment by edwinzhng** [comment]
Fixed by #65
