### ISSUE TITLE
Add shout out to Colin

### ISSUE THREAD

**Issue by lintool** [castorini/covidex#8]
I'd send a PR myself if I knew what to do wrt this new space-aged technology:
https://github.com/castorini/covidex/blob/master/client/src/components/HomeText.tsx

What happened to just writing HTML...?

We should add a a shout out to Colin in the landing page.

> Special thanks to [Colin Raffel](https://colinraffel.com/) for his help in pretraining T5 models for the biomedical domain.

**Comment by edwinzhng** [comment]
Done

**Comment by lintool** [comment]
Actually, next chance you get, remove the paragraph break, just merge it with the previous paragraph. Thanks!

**Comment by edwinzhng** [comment]
Done
