### ISSUE TITLE
Docker image + index modification request

### ISSUE THREAD

**Issue by zayyargla** [castorini/covidex#91]
I would like to request a development of docker image with environments set up and advice how to modify the API to use a custom index (might have to disable some components such as related article) as the web client is very well made. I would like to use it for a topic annotation based project where the web UI with centralised index would be used across the team, ensuring consistency.

Mainly I would like the following feature:
- docker image with configurable properties to point to a custom index and to disable gpu components.

**Comment by lintool** [comment]
Hi @zayyargla thanks for your interest - indeed we are working on generalizing Covidex to other indexes, e.g., https://www.aclweb.org/anthology/2020.sdp-1.19/ - instructions are coming soon!
